# Generated by Django 4.2.4 on 2023-08-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_passwordreset_valid_til'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='valid_til',
            field=models.DateTimeField(),
        ),
    ]
