# Generated by Django 4.2.4 on 2023-08-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_passwordreset_valid_til'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='password_update',
            field=models.BooleanField(default=False),
        ),
    ]
