# Generated by Django 4.2.4 on 2023-08-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_passwordreset_password_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
