# Generated by Django 4.2.4 on 2023-10-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
