# Generated by Django 4.2.4 on 2023-10-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='password',
        ),
    ]
